version: '3.9'
services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "8080:3000" # Порт, на котором будет работать ваше приложение
    networks:
      - my_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Пробрасываем порт 80 для HTTP-запросов
      - "443:443" # Порт HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Привязываем конфигурацию Nginx
      - /etc/letsencrypt:/etc/letsencrypt # Путь к сертификатам
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
